name: cat-leap-actions

on:
  push:
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install poetry
        run: poetry install
      - name: Run black
        run: poetry run black --check
      - name: Run pylint
        run: poetry run pylint